### ISSUE TITLE
How to get the holder?

### ISSUE THREAD

**Issue by coherenceNFT** [rohanmc/solsnatcher_metadata#1]
Hello,
it's possible to get the current holder of the token?

**Comment by rohanmc** [comment]
sorry for the delay
added example https://github.com/rohanmc/solsnatcher_metadata/blob/master/tokenowner.py for getting the owner address as well as usage in the README.
there might be a better way to do this, but I'm still learning my way around the ecosystem.
1. get the token-owner for the specific token's address - that token-owner address will be derived from the actual asdress
2. to get the actual address we make an spl-token call to get account info
the equivalent of 2 in the command line would be
spl-token account-info  --address 5CSdCgi2V5VX3Y54MfrYHa3y3Zafs3pXGQd1oH4Zpduv -u m
where 5CSdCgi2V5VX3Y54MfrYHa3y3Zafs3pXGQd1oH4Zpduv is the token-owner address

again, if someone finds a simpler way, i'd love to see that :) should be possible to get both the token-account as well as the owner of the token-account in the same API call

**Comment by rohanmc** [comment]
just leaving the issue open in case you've already found a better way @coherenceNFT
